version: '3'

services:  

  redis:
    image: redis:latest
    container_name: redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /app/app.py
    environment: 
      - CELERY_BROKER_URL=redis://redis:6379/0 
      - CELERY_RESULT_BACKEND=redis://redis:6379/0 
    volumes:
      - .:/app 
    ports:
      - "5555:5000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - CELERY_BROKER_URL=redis://redis:6379/0 
      - CELERY_RESULT_BACKEND=redis://redis:6379/0 
    # omit the concurrency argument to get a pool of workers equal to the number of platform cpus
    command: celery -A app.celery worker --loglevel=info --concurrency=4
    volumes:
      - .:/app
